apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-app
  namespace: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote-app
  template:
    metadata:
      labels:
        app: quote-app
    spec:
      containers:
        - name: quote-app
          image: prabhakarsrihari/k8s-quote-of-the-day:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 200m
          livenessProbe:
            httpGet:
              path: /api/status
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/status
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

