apiVersion: v1
kind: Service
metadata:
  name: quote-app-service
  namespace: webapp
spec:
  selector:
    app: quote-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

